version: '3.8'
services:
  backend:
    build: ./src/backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data  # Mount data folder
    restart: unless-stopped

  frontend:
    build: ./src/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    # environment:
    #   - API_URL=http:
    restart: unless-stopped